### PR TITLE
Added Julia implementation

### PR DESCRIPTION
**Pull request by ayman-albaz**
Added Julia implementation.
Seems to run nearly ~1.5x slower than Java. 
Used the python3 source code as a template for the Julia script. 
Haven't attempted to optimize it.

*Update: New Commit c58a282 improved time drastically. Now Julia runtime is within ~10ms of Java runtime. All in less than 100 lines of code!

### CODE REVIEW

**Review by jfuerth — COMMENTED** [review]
Hey, thanks for the contribution!

I'm not sure the playing field is quite level yet, but it's an impressive performance nonetheless!

The times quoted for all other interpreted/semicompiled languages are the real wall-clock time of running the interpreter from scratch. So that includes parse time, JIT compile time, warmup time, etc. Each language does get 5 tries in a row, so at least the the interpreter, standard library, and sourcecode/bytecode will almost certainly be coming from the page cache.

I tried allowing the Java implementation a warmup run, and measure the second run internally (discounting all the above factors) and I got this:

```
$ ./measure.sh 
Performance for java
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
Building...

real	0m0.854s
user	0m1.655s
sys	0m0.097s
Running...
Games played:    275692
Solutions found:   3100
Time elapsed:       360ms

real	0m1.225s
user	0m2.269s
sys	0m0.158s
Games played:    275692
Solutions found:   3100
Time elapsed:       357ms

real	0m1.165s
user	0m2.191s
sys	0m0.147s
Games played:    275692
Solutions found:   3100
Time elapsed:       360ms

real	0m1.160s
user	0m2.143s
sys	0m0.142s
Games played:    275692
Solutions found:   3100
Time elapsed:       466ms

real	0m1.293s
user	0m2.213s
sys	0m0.143s
Games played:    275692
Solutions found:   3100
Time elapsed:       362ms

real	0m1.191s
user	0m2.234s
sys	0m0.144s
Done!
```

The "time elapsed" for each of those runs is the internally measured time of solving the game the second time: min 362ms, max 466ms, mean 381ms.

The other difference is that all other implementations perform sanity checking on applying a move to GameState (checking for legality of both calls to occupiedHoles.remove() and making sure the target of the jump is not already occupied) and throws an exception or returns an error value–whatever the language's custom is for an abnormal/erroneous function result.

I'm happy to merge this and level the playing field (eg. add the state invariant checks, and take out the internal warmup run) or we could even update all the other languages to give them the same advantage, and report both measurements.

WDYT?

**Comment by jfuerth** [comment]
For reference, here's the times on my machine (I added time to measure.sh to enable comparison with the above, but I'm still just looking at the internally measured times for the second run):

```
julia$ ./measure.sh
Performance for julia
julia version 1.5.3
Building...
Running...
  0.583979 seconds (4.80 M allocations: 562.108 MiB, 36.29% gc time)
Games played: 137846
Games solution: 20150

real	0m1.699s
user	0m1.677s
sys	0m0.235s
  0.594168 seconds (4.80 M allocations: 562.108 MiB, 37.74% gc time)
Games played: 137846
Games solution: 20150

real	0m1.712s
user	0m1.695s
sys	0m0.237s
  0.593843 seconds (4.80 M allocations: 562.108 MiB, 37.04% gc time)
Games played: 137846
Games solution: 20150

real	0m1.798s
user	0m1.683s
sys	0m0.266s
  0.587317 seconds (4.80 M allocations: 562.108 MiB, 36.35% gc time)
Games played: 137846
Games solution: 20150

real	0m1.683s
user	0m1.681s
sys	0m0.232s
  0.588221 seconds (4.80 M allocations: 562.108 MiB, 36.52% gc time)
Games played: 137846
Games solution: 20150

real	0m1.724s
user	0m1.686s
sys	0m0.236s
Done!
```

On my machine, Min 583ms, Max 594ms, Mean 589ms. ~200ms or 64% slower. But still faster than C with malloc :)

**Comment by ayman-albaz** [comment]
Added a couple of changes be1d75baca10f9937f23afb99cb155d2eadc169a:
- I think I may have figured out what's going on. I was emulating your python3 code when in reality I should have been emulating your Java code. This caused me to miss a couple of performance tricks such as keeping my structs immutable instead of mutable.
- I've also added things that were missing such as sanity checks (which are a performance cost).
- I've removed the internal first run (I did it before to avoid JIT penalty).


On your point about changing this benchmark challenge, I think you should keep everything the way it is, less work for you obviously, and the fewer mistakes you'd make by re-writing things. 

Now that I've changed my code, these benchmarks should be similar.


I've tested Java and Julia on Windows (WSL2 so really Linux) and MacOs. Note I'm only interested in the internal runtime, instead of the runtime provided through the bash timer. This is because, for me, I would probably compile the program beforehand to avoid any slowdowns that arise from running Julia from the command-line and JIT latency issues. If I were doing something like this for production, it would probably be pre-compiled.

Here's a TLDR of the results below:
- On Windows (WSL2), Java and Julia seem to similar to one another. Julia's time seems to be a bit more unstable, but it's also slightly faster than Java.
- On MacOS, Java seems to be the clear winner by almost 60 milliseconds. No idea why this happens but it could be because of compiler issues that arise from Julia's immaturity as a language in comparison with Java's maturity.

If you can manage to get similar results on your PC, then feel free to merge away!

Windows (WSL2) Java:
```bash
Performance for java
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
Building...

real    0m1.200s
user    0m2.514s
sys     0m0.232s
Running...
Games played:    137846
Solutions found:   1550
Time elapsed:       440ms

real    0m0.553s
user    0m1.168s
sys     0m0.080s
Games played:    137846
Solutions found:   1550
Time elapsed:       477ms

real    0m0.593s
user    0m1.098s
sys     0m0.145s
Games played:    137846
Solutions found:   1550
Time elapsed:       470ms

real    0m0.603s
user    0m1.171s
sys     0m0.079s
Games played:    137846
Solutions found:   1550
Time elapsed:       502ms

real    0m0.630s
user    0m1.244s
sys     0m0.112s
Games played:    137846
Solutions found:   1550
Time elapsed:       481ms
Done!
```

Windows (WSL2) Julia:
```bash
Performance for julia
julia version 1.5.3
Building...
Nothing to do

real    0m0.000s
user    0m0.000s
sys     0m0.000s
Running...
  0.485002 seconds (4.47 M allocations: 547.282 MiB, 18.71% gc time)
Games played: 137846
Games solution: 20150

real    0m1.027s
user    0m1.218s
sys     0m0.528s
  0.444742 seconds (4.47 M allocations: 547.282 MiB, 21.00% gc time)
Games played: 137846
Games solution: 20150

real    0m0.944s
user    0m1.230s
sys     0m0.431s
  0.439276 seconds (4.47 M allocations: 547.282 MiB, 20.48% gc time)
Games played: 137846
Games solution: 20150

real    0m0.947s
user    0m1.265s
sys     0m0.398s
  0.450916 seconds (4.47 M allocations: 547.282 MiB, 21.14% gc time)
Games played: 137846
Games solution: 20150

real    0m0.951s
user    0m1.172s
sys     0m0.497s
  0.450026 seconds (4.47 M allocations: 547.282 MiB, 21.17% gc time)
Games played: 137846
Games solution: 20150

real    0m0.950s
user    0m1.125s
sys     0m0.542s
Done!
```

MacOS Java:
```bash
Performance for java
openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)
OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)
Building...

real	0m0.608s
user	0m1.047s
sys	0m0.084s
Running...
Games played:    137846
Solutions found:   1550
Time elapsed:       276ms

real	0m0.383s
user	0m0.724s
sys	0m0.058s
Games played:    137846
Solutions found:   1550
Time elapsed:       271ms

real	0m0.377s
user	0m0.715s
sys	0m0.057s
Games played:    137846
Solutions found:   1550
Time elapsed:       277ms

real	0m0.398s
user	0m0.740s
sys	0m0.060s
Games played:    137846
Solutions found:   1550
Time elapsed:       265ms

real	0m0.385s
user	0m0.705s
sys	0m0.059s
Games played:    137846
Solutions found:   1550
Time elapsed:       266ms

real	0m0.373s
user	0m0.705s
sys	0m0.060s
Done!
```

MacOS Julia:
```bash
Performance for julia
julia version 1.5.3
Building...
Nothing to do

real	0m0.001s
user	0m0.000s
sys	0m0.000s
Running...
  0.333529 seconds (4.47 M allocations: 547.282 MiB, 8.56% gc time)
Games played: 137846
Games solution: 20150

real	0m0.833s
user	0m1.197s
sys	0m0.180s
  0.333126 seconds (4.47 M allocations: 547.282 MiB, 8.56% gc time)
Games played: 137846
Games solution: 20150

real	0m0.795s
user	0m1.183s
sys	0m0.153s
  0.324675 seconds (4.47 M allocations: 547.282 MiB, 8.47% gc time)
Games played: 137846
Games solution: 20150

real	0m0.785s
user	0m1.163s
sys	0m0.167s
  0.323427 seconds (4.47 M allocations: 547.282 MiB, 8.60% gc time)
Games played: 137846
Games solution: 20150

real	0m0.787s
user	0m1.171s
sys	0m0.151s
  0.334193 seconds (4.47 M allocations: 547.282 MiB, 8.31% gc time)
Games played: 137846
Games solution: 20150

real	0m0.812s
user	0m1.188s
sys	0m0.157s
Done!
```

**Comment by jfuerth** [comment]
This is great, thanks so much for the contribution!

**Pull request merged**
